### ISSUE TITLE
flickr30k upperbound

### ISSUE THREAD

**Issue by volkancirik** [jnhwkim/ban-vqa#12]
Hello,

I used [Bottom-up Attention](https://github.com/peteanderson80/bottom-up-attention) to get boxes for Flickr30k data. Unfortunately, I could not get the same upperbound you reported in the paper. I get 0.6507 you reported 0.8745. Do you mind providing the details how you used Bottom-up model for inducing boxes. Below I listed mine:

```
model_name: resnet101_faster_rcnn_final.caffemodel
conf_thresh=0.2
min_boxes=10
max_boxes=100
```
UPDATE:

When I increase the number of boxes I get better upperbound but still it is not as good as yours, below setup gives me upperbound 0.8530

```
model_name: resnet101_faster_rcnn_final.caffemodel
conf_thresh=0.01
min_boxes=200
max_boxes=200
```

**Comment by jaesuny** [comment]
Did you train [Bottom-Up Attention](https://github.com/peteanderson80/bottom-up-attention) model yourself?
When I used Bottom-up Attention [model pretrained on Visual Genome](
https://storage.googleapis.com/bottom-up-attention/resnet101_faster_rcnn_final.caffemodel), I got upper bound about 0.87.

**Comment by volkancirik** [comment]
No I did not train. what are the hyperparameters that you use for running the model?

**Comment by jaesuny** [comment]
I just ran `tools/genenerate_tsv.py` of [Bottom-up Attention](
https://github.com/peteanderson80/bottom-up-attention)

As default,
model_name: resnet101_faster_rcnn_final.caffemodel
conf_thresh=0.2
min_boxes=10
max_boxes=100

**Comment by upccpu** [comment]
Hi,could you tell me which kind of GPUs you used,I use two titan Xp to run this only to show  'out of memory'.Thanks a lot.

**Comment by jd730** [comment]
@upccpu They used 4 GPU(12GB each) See [this](https://github.com/jnhwkim/ban-vqa/wiki/Troubleshooting#preprocessing-checklist)
