### ISSUE TITLE
Run test get KeyError: 1 error

### ISSUE THREAD

**Issue by Ailln** [jnhwkim/ban-vqa#17]
when I run `python test.py --label mytest`, get this error:
```bash
Traceback (most recent call last):
  File "test.py", line 91, in <module>
    eval_dset = VQAFeatureDataset(args.split, dictionary, adaptive=True)
  File "/home/gwh/Downloads/ban-vqa-master/dataset.py", line 244, in __init__
    self.entries = _load_dataset(dataroot, name, self.img_id2idx, self.label2ans)
  File "/home/gwh/Downloads/ban-vqa-master/dataset.py", line 142, in _load_dataset
    entries.append(_create_entry(img_id2val[img_id], question, None))
KeyError: 1
```
I find `data/test2015_imgid2idx.pkl` is `{}`, the file is generated with `python3 tools/adaptive_detection_features_converter.py`.

Can you help me? @jnhwkim Thanks in advance for any suggestions.

**Comment by callmetesla** [comment]
@HaveTwoBrush  can you post the fix for this issue?

**Comment by HaveTwoBrush** [comment]
OK

Arun Baalaaji <notifications@github.com> 于2019年3月10日周日 上午1:03写道：

**Comment by Ailln** [comment]
The reason is the lack of some data, please check your data carefully.

**Comment by callmetesla** [comment]
@HaveTwoBrush Thanks for the tip. Apparently i was missing the test2015 directory(ms-coco).
