### ISSUE TITLE
tools/download.sh does not work properly

### ISSUE THREAD

**Issue by mybirth0407** [jnhwkim/ban-vqa#24]
I read your paper very enjoyable.
However, there is a small problem with code execution.

http://visualq.org/ related links in download.sh do not work.
Does the link in https://visualqa.org/download.html work as expected?

Thank you for your research.

**Comment by jnhwkim** [comment]
Thanks for letting us know. This issue is resolved with a commit of e1bd40bc779f8ce77ae88b20a22c83b90030f27f.
