### ISSUE TITLE
Which files are needed for inference only?

### ISSUE THREAD

**Issue by mybirth0407** [jnhwkim/ban-vqa#25]
I want to only inference using this model.

Is it possible to have only the pre-trained model file for inference?
If not, should I run both download.sh and download_data.sh for inference only?

**Comment by jnhwkim** [comment]
For now, please refer to `demo` branch, especially, [this function](https://github.com/jnhwkim/ban-vqa/blob/695678d09f19750eec8f1667100973cfe1753f01/demo/server.py#L73), to make your own code. You don't need to download the whole dataset, which is for training.
