### ISSUE TITLE
Do you use the VG dataset to get the results on validation set

### ISSUE THREAD

**Issue by dhlrd** [jnhwkim/ban-vqa#27]
Hi Kim:
Thanks for your excellent work and code

Did you use the visual genome dataset for training to get the results on validation set which is listed in table 1 in your paper? As you compared with bottom-up and top-down results which used the VG dataset, so I assume you also used the VG dataset + VQA 2.0 train to get the final results on validation set, am i right ?

**Comment by jnhwkim** [comment]
No, it is not. In Table 1, we do **not** use Visual Genome QA dataset and do **not** use the counter module. You can take advantage of both of them.
