### ISSUE TITLE
Question about Visual Genome version

### ISSUE THREAD

**Issue by Ailln** [jnhwkim/ban-vqa#28]
hi, @jnhwkim  I have a question about visual genome version.

I find visual genome version is 1.2 in `README.md`.
![image](https://user-images.githubusercontent.com/7982046/55903864-295a0980-5c01-11e9-9d8c-c504157c31dc.png)

but in `dataset.py`, the 1.2 version of `image_data.json` does not have a key called `id`, this key in version 1.0.
![image](https://user-images.githubusercontent.com/7982046/55903485-56f28300-5c00-11e9-9b88-46e264c9eddc.png)

the 1.2 version example:
![image](https://user-images.githubusercontent.com/7982046/55904038-848bfc00-5c01-11e9-87a1-162ce5b4414b.png)

so which version should I use?

thank you first!

**Comment by jnhwkim** [comment]
@Jaesuny @btjhjeon any thought on this?

**Comment by jnhwkim** [comment]
Sorry for the late response. PR#38 solves your issue?
