### ISSUE TITLE
Why the learning rate is different with or without evalLoader ?

### ISSUE THREAD

**Issue by jiasenlu** [jnhwkim/ban-vqa#30]
Hi JinHwa:

I wonder why the learning rate is different with or without evalLoader? Thanks in advance!

Best
Jiasen

**Comment by jnhwkim** [comment]
Without evalLoader, which means for test-dev/test-standard splits, we greedily use both train/val splits, so we empirically lower the learning rate since it has more examples to train.

**Comment by jiasenlu** [comment]
Thanks!

**Comment by jnhwkim** [comment]
You’re welcome!
