### ISSUE TITLE
error when using adaptive_detection_features_converter.py

### ISSUE THREAD

**Issue by dhruvsharma15** [jnhwkim/ban-vqa#37]
While running adaptive_detection_features_converter.py for the TSV files, I am getting this error and can't resolve it. Any leads here would be helpful. This error occurs when trying to decode the features/boxes from the tsv file.

File "tools/adaptive_detection_features_converter.py", line 156, in extract
    bboxes = np.frombuffer(base64.decodestring(item['boxes']), dtype=np.float32).reshape((item['num_boxes'], -1))
  File "/home/reddy/myvenv/lib/python3.6/base64.py", line 554, in decodestring
    return decodebytes(s)
  File "/home/reddy/myvenv/lib/python3.6/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by jnhwkim** [comment]
I am afraid I have no idea about this issue. It may be related to the decoding issue?

**Comment by jnhwkim** [comment]
I believe you should try to explicitly use utf-8 decoding for this case. 
Since this thread is not active, I close this. Feel free to reopen this issue if you have any additional information.
