### ISSUE TITLE
Evaluating pretrained  model

### ISSUE THREAD

**Issue by claudiogreco** [jnhwkim/ban-vqa#4]
Hello,

I am trying to evaluate the pretrained model on the VQA dataset. If possible, I would like to ask you the following questions:

1) I executed the command "python3.6 evaluate.py". However, in that case, the script returns the following error:
```
Evaluate a given model optimized by training split using validation split.
loading dictionary from data/dictionary.pkl
loading features from h5 file
Traceback (most recent call last):
  File "evaluate.py", line 47, in <module>
    model.load_state_dict(model_data.get('model_state', model_data))
  File "/home/claudio.greco/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.w_emb.emb_.weight" in state_dict'
```
Probably, this happens because the default parameters of the script do not match the ones of the pretrained model. Am I right?

2) In order to solve problem (1), I executed the command "python3.6 evaluate.py. --num_hid=1280 --op='c' --gamma=8". In this case, it works, but the script returns the result "eval score: 82.23 (92.66)", which seems a bit too high to me. With what row and table in the paper should I compare this result to?

3) I tried to evaluate the pretrained model on the test split of the VQA dataset by changing "eval_dset = VQAFeatureDataset('dev', dictionary, adaptive=True)" to "eval_dset = VQAFeatureDataset('test2015', dictionary, adaptive=True)" in the evaluate.py script. However, in that case, the script returns the following error:
```
Evaluate a given model optimized by training split using validation split.
loading dictionary from data/dictionary.pkl
loading features from h5 file
/mnt/8tera/claudio.greco/ban-vqa/language_model.py:95: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  output, hidden = self.rnn(x, hidden)
Traceback (most recent call last):
  File "evaluate_new.py", line 51, in <module>
    eval_score, bound, entropy = evaluate(model, eval_loader)
  File "/mnt/8tera/claudio.greco/ban-vqa/train.py", line 121, in evaluate
    batch_score = compute_score_with_logits(pred, a.cuda()).sum()
  File "/mnt/8tera/claudio.greco/ban-vqa/train.py", line 26, in compute_score_with_logits
    one_hots.scatter_(1, logits.view(-1, 1), 1)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```
Do you know why this is happening?

Thank you very much!

**Comment by jnhwkim** [comment]
The pretrained model is trained on train/val splits. That's why the score is higher than your expectation. To get a json result file you may want to use this command:
```
$ python3 test.py --label mytest
```
Then, the json file will be located in `results/` directory. You can evaluate the result using the remote server in `https://evalai.cloudcv.org`.

**Comment by Ailln** [comment]
Submit in this [page](https://evalai.cloudcv.org/web/challenges/challenge-page/163/submission)?
