### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by shirleysu8** [jnhwkim/ban-vqa#40]
Hello, 

I'd like to use the model, I expect to enter a question in string, and an image path, but in the test.py, the input is the saved model, I am wondering where to input the question and image to test the model?

**Comment by jnhwkim** [comment]
I am worried that you may misunderstand the `test.py`; it outputs the results as the JSON format for evaluation. Have you checked this script `https://github.com/jnhwkim/ban-vqa/blob/demo/demo/server.py`? This would be a reference for your scenario.
