### ISSUE TITLE
Attention Visualization

### ISSUE THREAD

**Issue by mokadyr** [jnhwkim/ban-vqa#42]
Hi,
Love your work and repository

Just want to now how can I get the attention visualization? (like Figures 3,4 in the paper)

**Comment by jnhwkim** [comment]
Unfortunately, we do not provide the code for the visualization. Instead, you can try your own using `att` in https://github.com/jnhwkim/ban-vqa/blob/bcb6e28cf80046f615eb1bd53656c2cb09db31e6/base_model.py#L52 
`att` is a 4-dimensional tensor having attentional weights, (batch) x (glimpse) x (visual) x (language). Happy coding! 👨‍💻
