### ISSUE TITLE
Download Flickr30k  features

### ISSUE THREAD

**Issue by drigoni** [jnhwkim/ban-vqa#46]
Dear authors,

I am following the instruction reported in file `./tools/download_flickr.sh`.
I have succeeded in downloading the Flickr30k Image Features: [(Link: https://drive.google.com/file/d/1BmcxeY1kXzMZv54d4wMtl7HGc8Cs9zgO/view?usp=sharing)](https://drive.google.com/file/d/1BmcxeY1kXzMZv54d4wMtl7HGc8Cs9zgO/view?usp=sharing), but I am not able to unzip the file due to an error. I tried different ways to unzip it but I am not able to do it.
Could you please check the file?

Best regards,
Davide

**Comment by jnhwkim** [comment]
I believe the link is alive. Could you retry from the beginning, if you don't mind? An incomplete downloading may not let you unzip.

**Comment by jnhwkim** [comment]
I confirmed that the downloading link works fine including unzip for me.

**Comment by drigoni** [comment]
Thanks for the reply.
I have tried two different Linux systems and have also tried on Windows. I can download the package but not unzip it because it gives me an error with the `train.hdf5` file. It says the file is corrupted. I also tried two different connections. I can't unzip without errors. I have tried to download the file several times, but the result is always the same.
However, I correctly download and unzip the features that are reported in this link: https://github.com/jnhwkim/ban-vqa/issues/44 (https://drive.google.com/file/d/1Rdu8UDEi4Z0lnMaqwQYJKBeNTnSY-dsw/view?usp=sharing).

Could you please check the `train.hdf5` file?
Davide
