### ISSUE TITLE
Error in Flickr30k features

### ISSUE THREAD

**Issue by drigoni** [jnhwkim/ban-vqa#48]
Dear authors,

I saw your previous answer, but I didn't have time to answer before the issue was closed.
I have tried two different Linux systems and have also tried on Windows. I have tried Chrome and Firefox. I can download the package but not unzip it because it gives me an error with the `train.hdf5` file. It says the file is corrupted. I also tried two different internet connections. I can't unzip without errors. I have tried to download the file several times, but the result is always the same.

Could you please check the `train.hdf5` file? 
Davide

_Originally posted by @drigoni in https://github.com/jnhwkim/ban-vqa/issues/46#issuecomment-1137563064_

**Comment by jnhwkim** [comment]
I checked and confirmed it is able to unzip from this link: https://drive.google.com/file/d/1BmcxeY1kXzMZv54d4wMtl7HGc8Cs9zgO/view 
If you persist, I will recheck with this link.

**Comment by jnhwkim** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/1910051/171825294-ebe56f3d-2fa8-4705-814f-8c61a7edab4b.png">
I confirmed that the download link has no issue. Unzipping and reading `train.hdf5` works fine, as above screenshot.
