### ISSUE TITLE
link no longer works

### ISSUE THREAD

**Issue by Nnnaqooooo** [jnhwkim/ban-vqa#49]
Dear authors:
the link image metadata and question answers of VQA are no longer works.could you support it again?

**Comment by jnhwkim** [comment]
Did you check [this](https://visualqa.org/download.html) download page?

**Comment by jnhwkim** [comment]
Regrettably, the link is no longer accessible, and I cannot perform maintenance due to the loss of the materials. :(
Sorry that I'm archiving this repository for this reason.
