### ISSUE TITLE
Trouble creating ID.pkls

### ISSUE THREAD

**Issue by MaximilianLindholz** [jnhwkim/ban-vqa#50]
Hello :) 

first of all thank you for sharing your repo!

i  am having trouble creating those files: 
        indices_file = {
            'train': 'data/train_imgid2idx.pkl',
            'val': 'data/val_imgid2idx.pkl',
            'test': 'data/test2015_imgid2idx.pkl'}
        ids_file = {
            'train': 'data/train_ids.pkl',
            'val': 'data/val_ids.pkl',
            'test': 'data/test2015_ids.pkl'}

because the utils.py demands .jpeg images to create the indexes which are not created at this point. Could you be so kind to share the id.pkls?

thank you and best regards
Max

**Comment by jnhwkim** [comment]
Regrettably, the link is no longer accessible, and I cannot perform maintenance due to the loss of the materials. :(
Sorry that I'm archiving this repository for this reason.
