### ISSUE TITLE
How to use the pre

### ISSUE THREAD

**Issue by MILOTIDE** [jnhwkim/ban-vqa#6]
Hello,
   I'm the first time try to use a vqa network, and I wonder how can I use the pretrained model to ask a question on a image and get a response? Thank you.

**Comment by jnhwkim** [comment]
Demo is currently not available. If you contribute, we will greatly appreciate!

**Comment by MILOTIDE** [comment]
When I searched in github, I found the vqa demos  almost run on web, is this necessary? Can it run in the terminal?

**Comment by jnhwkim** [comment]
You may need some hassle to work with this repo. We don't have a ready-to-run code for that. However, I have a plan for the demo. Stay tuned!

**Comment by kevgeo** [comment]
@MILOTIDE You could definitely run it on terminal but a better way to display a demo in python would be through a juptyer notebook like this [one](https://github.com/peteanderson80/Up-Down-Captioner/blob/master/scripts/demo.ipynb).
