### ISSUE TITLE
Flickr30K evaluation?

### ISSUE THREAD

**Issue by farleylai** [jnhwkim/ban-vqa#8]
It seems like the Flickr30K grounding task in the report is not included in the repo.
Am I missing something?

**Comment by jnhwkim** [comment]
As the title of this repository indicates, it is for the visual question answering task. However, we plan to publish for the other tasks, Flickr30k Entities, VizWiz, etc., within this year.

**Comment by farleylai** [comment]
OK, looking forward to the release.
